name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '21 14-23/1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run a one-line script
      run: |
        echo " " >> README.md
        git config user.name "Suresh Shrestha"
        git config user.email "sureshcstha@gmail.com"
        git add .
        git commit -m "a minor change"
        git push
